### ISSUE TITLE
Prefer arrow functions over bind(this)

### ISSUE THREAD

**Issue by beaufortfrancois** [futomi/html5-CC2650SensorTag.js#1]
First of all, great job @futomi! What an awesome library ;)

I've noticed you were using `bind(this)` and wondered if we could make code simpler to read with arrow functions. What do you think of this below?

```diff
-       char.oncharacteristicvaluechanged = function(event) {
+       char.oncharacteristicvaluechanged = event => {
                if(this.onmovementnotify && typeof(this.onmovementnotify) === 'function') {
                        var dataview = event.target.value;
                        var data = this._parseDataValueMovement(dataview);
                        this.onmovementnotify(data);
                }
-       }.bind(this);
+       };

**Comment by futomi** [comment]
Thank you so math for your advice. Yes, you are right. I coded in an old-fashioned way by habit. I'll update the library soon. Thank you again.

**Comment by futomi** [comment]
I updated the codes. Thank you.

**Comment by beaufortfrancois** [comment]
Cool! By the way, I've shared your library to the Web Bluetooth community at https://plus.google.com/communities/108953318610326025178

**Comment by futomi** [comment]
It's a great honor. Thank you so match.
